ClusterName=cluster
SlurmctldHost=localhost

# MpiDefault=pmix

SlurmctldPidFile=/var/run/slurm/slurmctld.pid
SlurmctldPort=6817
SlurmdPidFile=/var/run/slurm/slurmd.pid
SlurmdPort=6818
SlurmdSpoolDir=/var/spool/slurmd
StateSaveLocation=/var/spool/slurmctld
# Optional: required when using srun with dynamic ports
# SrunPortRange=60001-63000

SlurmUser=slurm
SwitchType=switch/none

ProctrackType=proctrack/cgroup
TaskPlugin=task/affinity,task/cgroup
JobSubmitPlugins=lua

PropagateResourceLimitsExcept=MEMLOCK
ReturnToService=1

InactiveLimit=0
KillWait=30
MinJobAge=300
SlurmctldTimeout=300
SlurmdTimeout=300
Waittime=0

SchedulerType=sched/backfill #builtin
SelectType=select/cons_tres
SelectTypeParameters=CR_Core

MaxArraySize=100000
MaxJobCount=100000

# Disable preemption
PreemptMode=OFF
PreemptType=preempt/none
PriorityType=priority/multifactor
# No fair-share decay
PriorityDecayHalfLife=0
PriorityUsageResetPeriod=NONE
# Age is the only effective priority factor.
PriorityWeightAge=100000
PriorityWeightFairshare=0
PriorityWeightJobSize=0
PriorityWeightPartition=0
PriorityWeightQOS=0
PriorityMaxAge=7-0

AccountingStorageEnforce=associations,limits,qos
AccountingStorageType=accounting_storage/slurmdbd
AccountingStorageHost=localhost
# Store job comments in accounting database
AccountingStoreFlags=job_comment
PrivateData=accounts,reservations,usage,jobs,users

GresTypes=gpu
AccountingStorageTRES=gres/gpu

AcctGatherNodeFreq=0
JobAcctGatherFrequency=30
JobAcctGatherType=jobacct_gather/cgroup
JobCompHost=localhost
JobCompLoc=slurm_jobcomp_db
JobCompPass=password
JobCompPort=3306
JobCompType=jobcomp/mysql
JobCompUser=slurm
JobContainerType=job_container/none

SlurmctldDebug=info
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdDebug=info
SlurmdLogFile=/var/log/slurm/slurmd.log

AuthAltTypes=auth/jwt
AuthAltParameters=jwt_key=/var/spool/slurm/statesave/jwt_hs256.key,max_token_lifespan=1800

SlurmctldParameters=enable_configless

# Allow slurmd to expose L3 cache topology as socket
#SlurmdParameters=l3cache_as_socket

# Mail notification program
#MailProg=/usr/bin/mail

# OpenHPC interactive jobs
LaunchParameters=use_interactive_step

# Clean up jobs after completion
Epilog=/etc/slurm/slurm.epilog.clean

# Health check
HealthCheckProgram=/usr/sbin/nhc
HealthCheckInterval=300

# Suspend idle nodes after 30 minutes
SuspendTime=1800

# Maximum time allowed for node resume
ResumeTimeout=600

# Optional:
# SuspendProgram=/etc/slurm/suspend.sh
# ResumeProgram=/etc/slurm/resume.sh

# BurstBufferType=burst_buffer/datawarp
# FederationParameters=fed_display
# TopologyPlugin=topology/tree
# DebugFlags=Steps,Priority

Include partition.conf
Include node.conf
